### PR TITLE
Adds Alert bar example to the docs

### PR DESCRIPTION
**Pull request by jsdario**
As proposed here https://github.com/exponent/ex-navigation/pull/241#issuecomment-269032738

### CODE REVIEW

**Comment by sibelius** [comment]
LGTM

**Comment by sibelius** [comment]
@jsdario would u mind adding this as recipe here: https://github.com/sibelius/ex-navigation-recipes?

**Comment by jsdario** [comment]
@sibelius I am happy to contribute 😄 
I see that you have already appended it https://github.com/sibelius/ex-navigation-recipes/blob/master/recipes/AlertBarRedux.md

**Comment by jsdario** [comment]
Closing because this project seems legacy already https://github.com/expo/ex-navigation#an-important-note-about-the-future

**Pull request closed without merging**
