### PR TITLE
React.PropTypes => PropTypes, redux ^5.0.6

### PR DESCRIPTION
**Pull request by isnifer**
Hey, @skevy @brentvatne @janicduplessis  please, take a look!
At Tipsi we want to upgrade our app to RN 0.47 because the App even can't start.
This PR brings `prop-types` into ex-navigation 👍 
Also, I've update `react-redux` and fix paths to `storeShape`.

Please, publish updated version into npm we are waiting for you 😢

### CODE REVIEW

**Comment by isnifer** [comment]
Is anyone here? 
image

@skevy @brentvatne @janicduplessis

**Comment by isnifer** [comment]
Hey @skevy @brentvatne @janicduplessis, where are you?

**Comment by isnifer** [comment]
@skevy @brentvatne @janicduplessis
image

**Comment by brentvatne** [comment]
@isnifer - I don't work on this anymore, we are moving to ex-navigation, do you want to be a maintainer of this project?

**Comment by isnifer** [comment]
@brentvatne this project is `ex-navigation`, haha. If I need to be a maintainer to merge this PR, OK I will)

**Comment by brentvatne** [comment]
lol oops, I meant react-navigation :P

**Comment by brentvatne** [comment]
published in 3.1.0

**Comment by isnifer** [comment]
Awesome, thank you

**Pull request merged**
