### PR TITLE
Merge sharedElementTransitions example with the main example

### PR DESCRIPTION
**Pull request by satya164**

### CODE REVIEW

**Comment by satya164** [comment]
There's a crazy jumping going on with this example though. cc @janicduplessis

**Comment by skevy** [comment]
@janicduplessis any ideas on the "crazy jumping" haha?

**Comment by jozan** [comment]
Just tried this on my device (iPhone 5c) and saw no crazy jumping.

**Comment by satya164** [comment]
@jozan Try on Android

**Comment by jozan** [comment]
I have no Android device at hand at this moment and Genymotion wont start up due to errors. 😅

**Pull request closed without merging**
