### PR TITLE
use BackHandler instead of BackAndroid, fix #461

### LINKED ISSUE #461: BackAndroid is deprecated on RN44
We should use BackHandler instead

https://github.com/facebook/react-native/blob/f3dbddcf2bdc0e4f49dd6f5220360b5ff383e16f/Libraries/react-native/react-native-implementation.js#L70

### PR DESCRIPTION
**Pull request by sibelius**

### CODE REVIEW

**Comment by brentvatne** [comment]
@sibelius - can you use BackHandler if it is available, and otherwise use BackAndroid? otherwise this PR requires everyone to update to react-native 0.44

**Comment by chirag04** [comment]
i thought BackHandler is only deprecated but not removed. no?

**Comment by brentvatne** [comment]
@chirag04 - I think you have it backwards :> BackAndroid is deprecated and not removed

**Comment by chirag04** [comment]
ah right. 👍

**Comment by sibelius** [comment]
updated!

**Pull request closed without merging**
